In [8]:
import pandas as pd

In [15]:
df = pd.read_csv('file-input1.csv',header=None)

In [16]:
df

,0,1,2,3,4,5,6,7,8
0,8e66dea62a914ba69e48c534c705574e,2019-09-12T00:00:25.920Z,http://example.com/?url=091,user-028,ER,Chrome,Mac,501,0.6975
1,3897a5a7115d489e9ad7ddf51d0c8c58,2019-09-12T00:00:51.840Z,http://example.com/?url=067,user-032,SJ,Firefox,Linux,307,0.3905
2,baf865e583aa45f7994b668804560f3b,2019-09-12T00:01:17.760Z,http://example.com/?url=040,user-031,MA,Firefox,Linux,510,0.5118
3,656bd941b94044a18b45197c483393e7,2019-09-12T00:01:43.680Z,http://example.com/?url=161,user-057,GD,Edge,Linux,510,0.1552
4,a4156ae1faf74acc9e0706e9c53f0d29,2019-09-12T00:02:09.600Z,http://example.com/?url=104,user-054,ZW,Edge,Android,208,0.7311
...,...,...,...,...,...,...,...,...,...
9995,d8ea26e4706b48f79a7eecd0f4483f9f,2019-09-14T23:58:16.320Z,http://example.com/?url=105,user-074,EC,Opera,windows,507,0.4426
9996,24b893f93f4949509b8b4ba077a9743a,2019-09-14T23:58:42.240Z,http://example.com/?url=104,user-054,AU,IE,windows,226,0.9244
9997,ea5a9675f35d46b79fa07d41986776df,2019-09-14T23:59:08.160Z,http://example.com/?url=090,user-067,CU,IE,Android,511,0.2036
9998,4dc76bdc00ee4322b326ab6b19e44972,2019-09-14T23:59:34.080Z,http://example.com/?url=020,user-024,ER,Opera,Android,507,0.7050
9999,7aac76c8320347e5a33cf8b7ef86e241,2019-09-15T00:00:00Z,http://example.com/?url=008,user-001,MH,IE,windows,301,0.8516

In [25]:
df[1] = df[1].astype(str).apply(lambda x: x[:19])
df[1] = df[1].astype(str).apply(lambda x: x.replace('T',' '))

In [26]:
df

,0,1,2,3,4,5,6,7,8
0,8e66dea62a914ba69e48c534c705574e,2019-09-12 00:00:25,http://example.com/?url=091,user-028,ER,Chrome,Mac,501,0.6975
1,3897a5a7115d489e9ad7ddf51d0c8c58,2019-09-12 00:00:51,http://example.com/?url=067,user-032,SJ,Firefox,Linux,307,0.3905
2,baf865e583aa45f7994b668804560f3b,2019-09-12 00:01:17,http://example.com/?url=040,user-031,MA,Firefox,Linux,510,0.5118
3,656bd941b94044a18b45197c483393e7,2019-09-12 00:01:43,http://example.com/?url=161,user-057,GD,Edge,Linux,510,0.1552
4,a4156ae1faf74acc9e0706e9c53f0d29,2019-09-12 00:02:09,http://example.com/?url=104,user-054,ZW,Edge,Android,208,0.7311
...,...,...,...,...,...,...,...,...,...
9995,d8ea26e4706b48f79a7eecd0f4483f9f,2019-09-14 23:58:16,http://example.com/?url=105,user-074,EC,Opera,windows,507,0.4426
9996,24b893f93f4949509b8b4ba077a9743a,2019-09-14 23:58:42,http://example.com/?url=104,user-054,AU,IE,windows,226,0.9244
9997,ea5a9675f35d46b79fa07d41986776df,2019-09-14 23:59:08,http://example.com/?url=090,user-067,CU,IE,Android,511,0.2036
9998,4dc76bdc00ee4322b326ab6b19e44972,2019-09-14 23:59:34,http://example.com/?url=020,user-024,ER,Opera,Android,507,0.7050
9999,7aac76c8320347e5a33cf8b7ef86e241,2019-09-15 00:00:00,http://example.com/?url=008,user-001,MH,IE,windows,301,0.8516

In [28]:
df = df.astype(str).apply(lambda x: "'"+x+"'")

In [33]:
#df[7] = df[7].astype(str).apply(lambda x: x[1:-1])
#df[8] = df[8].astype(str).apply(lambda x: x[1:-1])

In [87]:
import random 
#row_list

In [152]:
#df[9] = df[9].astype(str).apply(lambda x: x.replace('Z',''))

In [155]:
df.iloc[row_list]

,0,1,2,3,4,5,6,7,8,9
49,"'ef08ec5106cb4e6fa71198719998b204',","'2019-09-12 00:21:36Z',","'http://example.com/?url=102',","'user-092',","'HM',","'Chrome',","'Mac',","422,","0.4,",'2019-09-12'
60,"'ee3051c817b840e8bc4cdac243d9ca10',","'2019-09-12 00:26:21Z',","'http://example.com/?url=016',","'user-017',","'QA',","'IE',","'Linux',","205,","0.9692,",'2019-09-12'
33,"'d7d20ff4ce03412398534386dcfa0185',","'2019-09-12 00:14:41Z',","'http://example.com/?url=164',","'user-069',","'KP',","'Firefox',","'windows',","500,","0.5031,",'2019-09-12'

In [172]:
row_list = [] 
for j in range(4): 
    row_list.append(random.randint(0, 50)) 

#row_list = [0,1,2,3]
#print('TRUNCATE hw10.hw10_p1;')
#print('BEGIN BATCH')
for row in row_list:
    print('INSERT INTO hw10.hw10_p1')
    print('(id, time, url, userId, country, ua_browser, ua_os, response_status, TTFB, date)')
    print('VALUES (uuid(),',end=' ')
    for i in range(1,9+1):
        print (df.loc[ df[4].isin(["'SN'," , "'SJ',"]) ].iloc[row][i],end =' ')
    print('); ')
#print('APPLY BATCH;')

INSERT INTO hw10.hw10_p1
(id, time, url, userId, country, ua_browser, ua_os, response_status, TTFB, date)
VALUES (uuid(), '2019-09-14 04:42:14Z', 'http://example.com/?url=144', 'user-061', 'SJ', 'Firefox', 'Android', 504, 0.243, '2019-09-14' );
INSERT INTO hw10.hw10_p1
(id, time, url, userId, country, ua_browser, ua_os, response_status, TTFB, date)
VALUES (uuid(), '2019-09-12 00:00:51Z', 'http://example.com/?url=067', 'user-032', 'SJ', 'Firefox', 'Linux', 307, 0.3905, '2019-09-12' );
INSERT INTO hw10.hw10_p1
(id, time, url, userId, country, ua_browser, ua_os, response_status, TTFB, date)
VALUES (uuid(), '2019-09-12 09:34:59Z', 'http://example.com/?url=013', 'user-076', 'SN', 'Chrome', 'IOS', 204, 0.6055, '2019-09-12' );
INSERT INTO hw10.hw10_p1
(id, time, url, userId, country, ua_browser, ua_os, response_status, TTFB, date)
VALUES (uuid(), '2019-09-12 16:37:55Z', 'http://example.com/?url=148', 'user-070', 'SN', 'Edge', 'Linux', 422, 0.8537, '2019-09-12' );

In [141]:
df.loc[df[4]=="'SN',"]

,0,1,2,3,4,5,6,7,8,9
439,"'0815c70d9e6a4d61a94f6159e42b4efe',","'2019-09-12 03:10:04Z',","'http://example.com/?url=155',","'user-094',","'SN',","'Edge',","'windows',","100,","0.9798,",'2019-09-12Z'
802,"'d22cbcd38a634d1a9e39e3bacaa0bc64',","'2019-09-12 05:46:53Z',","'http://example.com/?url=176',","'user-073',","'SN',","'Edge',","'IOS',","511,","0.431,",'2019-09-12Z'
1008,"'7d47de607ecd482dae6d4d2e0205862e',","'2019-09-12 07:15:53Z',","'http://example.com/?url=017',","'user-043',","'SN',","'IE',","'Linux',","599,","0.6282,",'2019-09-12Z'
1330,"'cdb4f1a2d3c8406ca5f022e120a5a206',","'2019-09-12 09:34:59Z',","'http://example.com/?url=013',","'user-076',","'SN',","'Chrome',","'IOS',","204,","0.6055,",'2019-09-12Z'
1436,"'ef61126a8e3f47d582132312024bd008',","'2019-09-12 10:20:47Z',","'http://example.com/?url=138',","'user-090',","'SN',","'Firefox',","'Linux',","503,","0.1645,",'2019-09-12Z'
1490,"'0e55888241a84429a1d581badc990763',","'2019-09-12 10:44:06Z',","'http://example.com/?url=111',","'user-036',","'SN',","'Edge',","'windows',","599,","0.5261,",'2019-09-12Z'
2130,"'97fd10341a2349389f283a6b5ff1a6a0',","'2019-09-12 15:20:35Z',","'http://example.com/?url=085',","'user-032',","'SN',","'Safari',","'windows',","507,","0.258,",'2019-09-12Z'
2159,"'d3ab4d67e577432e9c9e1fb6e93d2451',","'2019-09-12 15:33:07Z',","'http://example.com/?url=149',","'user-085',","'SN',","'Safari',","'Linux',","431,","0.0561,",'2019-09-12Z'
2309,"'942ce0f9c710422782d7a3dc77ea3489',","'2019-09-12 16:37:55Z',","'http://example.com/?url=148',","'user-070',","'SN',","'Edge',","'Linux',","422,","0.8537,",'2019-09-12Z'
2583,"'decd0ae4fd324bab92e000082d05b08f',","'2019-09-12 18:36:17Z',","'http://example.com/?url=053',","'user-056',","'SN',","'Edge',","'Mac',","413,","0.921,",'2019-09-12Z'
2685,"'81ba67b857224092adb780c463ec6641',","'2019-09-12 19:20:21Z',","'http://example.com/?url=169',","'user-018',","'SN',","'Safari',","'windows',","414,","0.2816,",'2019-09-12Z'
3798,"'851ee166570d4f568e81ea8582de17d9',","'2019-09-13 03:21:10Z',","'http://example.com/?url=162',","'user-019',","'SN',","'Firefox',","'Android',","408,","0.5322,",'2019-09-13Z'
4093,"'e983e333e94f4c67870fc2d87ecb201e',","'2019-09-13 05:28:36Z',","'http://example.com/?url=109',","'user-039',","'SN',","'Opera',","'windows',","502,","0.4698,",'2019-09-13Z'
4134,"'ee5d87357bb24ca0adfacfe282640d4f',","'2019-09-13 05:46:19Z',","'http://example.com/?url=140',","'user-070',","'SN',","'Safari',","'IOS',","307,","0.6803,",'2019-09-13Z'
4785,"'b1330006d30b494a8d02e500a72ac2c6',","'2019-09-13 10:27:33Z',","'http://example.com/?url=031',","'user-031',","'SN',","'Safari',","'IOS',","410,","0.5789,",'2019-09-13Z'
5232,"'a9a77811f33441b79e204914ca8e083e',","'2019-09-13 13:40:39Z',","'http://example.com/?url=112',","'user-024',","'SN',","'Firefox',","'Mac',","414,","0.136,",'2019-09-13Z'
5600,"'4924c877771b4e46907d2a68e314face',","'2019-09-13 16:19:37Z',","'http://example.com/?url=128',","'user-002',","'SN',","'Edge',","'IOS',","413,","0.259,",'2019-09-13Z'
6222,"'03d8be2a49614d1882586ac89fecc5f7',","'2019-09-13 20:48:20Z',","'http://example.com/?url=162',","'user-088',","'SN',","'IE',","'IOS',","502,","0.2182,",'2019-09-13Z'
6881,"'9ea1ee9af54e4b5b90a687ec593abbc6',","'2019-09-14 01:33:01Z',","'http://example.com/?url=149',","'user-009',","'SN',","'Edge',","'windows',","421,","0.7113,",'2019-09-14Z'
7170,"'8ec16d44ef8e40daa3785d422675faaf',","'2019-09-14 03:37:52Z',","'http://example.com/?url=070',","'user-066',","'SN',","'Edge',","'Android',","504,","0.2796,",'2019-09-14Z'
7213,"'34332377b62a4b2faff6583769d8eac6',","'2019-09-14 03:56:26Z',","'http://example.com/?url=078',","'user-079',","'SN',","'Firefox',","'Mac',","201,","0.2186,",'2019-09-14Z'
7897,"'6570e2d494f04f919d1869a4916010a9',","'2019-09-14 08:51:56Z',","'http://example.com/?url=168',","'user-009',","'SN',","'IE',","'windows',","201,","0.0201,",'2019-09-14Z'
8066,"'2eef63f5deb04093a0919dc8c2da8aff',","'2019-09-14 10:04:56Z',","'http://example.com/?url=021',","'user-049',","'SN',","'Edge',","'Mac',","444,","0.5906,",'2019-09-14Z'
8281,"'3db51daac3ee43e6a27d640d5df21109',","'2019-09-14 11:37:49Z',","'http://example.com/?url=108',","'user-067',","'SN',","'Edge',","'windows',","418,","0.9904,",'2019-09-14Z'
8596,"'0c272bb6010849b98e7e0c0012cc0a07',","'2019-09-14 13:53:54Z',","'http://example.com/?url=035',","'user-059',","'SN',","'IE',","'Android',","303,","0.2155,",'2019-09-14Z'
8611,"'973d1eef68394325bcaec7b10b21c92f',","'2019-09-14 14:00:23Z',","'http://example.com/?url=160',","'user-058',","'SN',","'Safari',","'Android',","451,","0.2665,",'2019-09-14Z'
8621,"'85a5734d009c4b298a05cdebaa662814',","'2019-09-14 14:04:42Z',","'http://example.com/?url=050',","'user-020',","'SN',","'Firefox',","'IOS',","302,","0.5235,",'2019-09-14Z'
8827,"'ed7d0702a60549059c64195519917189',","'2019-09-14 15:33:41Z',","'http://example.com/?url=041',","'user-066',","'SN',","'Edge',","'Mac',","202,","0.9048,",'2019-09-14Z'
8966,"'e39ff4ace1244f71b31833201bc890d8',","'2019-09-14 16:33:44Z',","'http://example.com/?url=195',","'user-020',","'SN',","'IE',","'Mac',","402,","0.7085,",'2019-09-14Z'
9305,"'c26e7e1a48064d39abdd980ec685d543',","'2019-09-14 19:00:11Z',","'http://example.com/?url=042',","'user-045',","'SN',","'Edge',","'Mac',","501,","0.1151,",'2019-09-14Z'
9544,"'424992a79bca4a3486482d212ce7d3a4',","'2019-09-14 20:43:26Z',","'http://example.com/?url=111',","'user-086',","'SN',","'Edge',","'Linux',","423,","0.0129,",'2019-09-14Z'
9561,"'6b4f985d3be74252895d0fdee96f0f7d',","'2019-09-14 20:50:47Z',","'http://example.com/?url=181',","'user-097',","'SN',","'Edge',","'Linux',","414,","0.1181,",'2019-09-14Z'
9757,"'dfa6b6611ac54040bd42093a77fd7842',","'2019-09-14 22:15:27Z',","'http://example.com/?url=174',","'user-029',","'SN',","'Chrome',","'windows',","421,","0.4289,",'2019-09-14Z'
9844,"'51116cb224074ac3a22386f71cd0e950',","'2019-09-14 22:53:02Z',","'http://example.com/?url=028',","'user-080',","'SN',","'Safari',","'IOS',","403,","0.4781,",'2019-09-14Z'
9901,"'6d8ed60bd9d54a4d8856737c8f625601',","'2019-09-14 23:17:39Z',","'http://example.com/?url=130',","'user-005',","'SN',","'IE',","'Linux',","226,","0.3586,",'2019-09-14Z'

In [132]:
df

,0,1,2,3,4,5,6,7,8,9
0,"'8e66dea62a914ba69e48c534c705574e',","'2019-09-12 00:00:25Z',","'http://example.com/?url=091',","'user-028',","'ER',","'Chrome',","'Mac',","501,","0.6975,",'2019-09-12Z'
1,"'3897a5a7115d489e9ad7ddf51d0c8c58',","'2019-09-12 00:00:51Z',","'http://example.com/?url=067',","'user-032',","'SJ',","'Firefox',","'Linux',","307,","0.3905,",'2019-09-12Z'
2,"'baf865e583aa45f7994b668804560f3b',","'2019-09-12 00:01:17Z',","'http://example.com/?url=040',","'user-031',","'MA',","'Firefox',","'Linux',","510,","0.5118,",'2019-09-12Z'
3,"'656bd941b94044a18b45197c483393e7',","'2019-09-12 00:01:43Z',","'http://example.com/?url=161',","'user-057',","'GD',","'Edge',","'Linux',","510,","0.1552,",'2019-09-12Z'
4,"'a4156ae1faf74acc9e0706e9c53f0d29',","'2019-09-12 00:02:09Z',","'http://example.com/?url=104',","'user-054',","'ZW',","'Edge',","'Android',","208,","0.7311,",'2019-09-12Z'
...,...,...,...,...,...,...,...,...,...,...
9995,"'d8ea26e4706b48f79a7eecd0f4483f9f',","'2019-09-14 23:58:16Z',","'http://example.com/?url=105',","'user-074',","'EC',","'Opera',","'windows',","507,","0.4426,",'2019-09-14Z'
9996,"'24b893f93f4949509b8b4ba077a9743a',","'2019-09-14 23:58:42Z',","'http://example.com/?url=104',","'user-054',","'AU',","'IE',","'windows',","226,","0.9244,",'2019-09-14Z'
9997,"'ea5a9675f35d46b79fa07d41986776df',","'2019-09-14 23:59:08Z',","'http://example.com/?url=090',","'user-067',","'CU',","'IE',","'Android',","511,","0.2036,",'2019-09-14Z'
9998,"'4dc76bdc00ee4322b326ab6b19e44972',","'2019-09-14 23:59:34Z',","'http://example.com/?url=020',","'user-024',","'ER',","'Opera',","'Android',","507,","0.705,",'2019-09-14Z'
9999,"'7aac76c8320347e5a33cf8b7ef86e241',","'2019-09-15 00:00:00Z',","'http://example.com/?url=008',","'user-001',","'MH',","'IE',","'windows',","301,","0.8516,",'2019-09-15Z'